builds:
  - id: boi
    main: ./cmd/boi
    binary: boi
    goos: [windows, linux, darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/boi-family/boi-cli/internal/cli.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      boi_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
